// [UI-008] blog-search.js — blog index search + category chips (behavior detail below)
// DOES:   client-side filtering of the generated blog index: the active chip AND the
//         search term combine; cards, section labels and counters show or hide, and
//         ?cat= deep links are read on load and written on every chip click.
// IN:     #blog-search input, .b-cat-btn chips, cards emitted by gen_blog_index.py
// OUT:    display toggles + history.replaceState on ?cat=; no DOM is ever created
// NOTES:  search input is debounced 150ms; accents are folded so "ore" matches "orë".
/* blog-search.js v3 - search + category filter for {en,it,sq}/blog/index.html.
   The page is generated by gen_blog_index.py; this file stays language-agnostic
   (every visible string lives in the page). Trusted-Types safe: no innerHTML.
   Behavior: chips AND search combine; the Latest strip (duplicates of the three
   newest, data-dup="1") hides whenever any filter is active so nothing appears
   twice; the featured card filters like a normal card of its category; section
   labels hide when their grid empties; ?cat= deep links are read and written. */
(function () {
  var input = document.getElementById('blog-search');
  var chips = [].slice.call(document.querySelectorAll('.b-cat-btn[data-filter]'));
  if (!input || !chips.length) return;
  var latest = document.getElementById('b-latest');
  var latestLabel = document.getElementById('b-latest-label');
  var countEl = document.getElementById('blog-count');
  var emptyEl = document.getElementById('blog-empty');
  var fold = String.prototype.normalize
    ? function (s) { return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }
    : function (s) { return s.toLowerCase(); };
  var items = [].map.call(document.querySelectorAll('.b-card,.b-feat'), function (c) {
    var h = c.querySelector('.b-card-title,.b-feat-title');
    var d = c.querySelector('.b-card-desc,.b-feat-desc');
    return { el: c, cat: c.getAttribute('data-cat') || '', dup: c.hasAttribute('data-dup'),
             text: fold((h ? h.textContent : '') + ' ' + (d ? d.textContent : '')) };
  });
  var total = 0;
  items.forEach(function (i) { if (!i.dup) total++; });
  var valid = chips.map(function (b) { return b.getAttribute('data-filter'); });
  var active = 'all';
  try {
    var q = new URL(location.href).searchParams.get('cat');
    if (q && q !== 'all' && valid.indexOf(q) > -1) active = q;
  } catch (e) {}

  // [UI-008.a] setChips — reflect the active category on the chip row
  // DOES:   sets aria-pressed on every chip so styling and screen readers both track
  //         which filter is live.
  function setChips() {
    chips.forEach(function (b) {
      b.setAttribute('aria-pressed', b.getAttribute('data-filter') === active ? 'true' : 'false');
    });
  }
  // [UI-008.b] apply — the single filter pass
  // DOES:   shows/hides every card from (active chip, folded term); hides the Latest
  //         strip and its duplicates whenever ANY filter is on so nothing appears
  //         twice; collapses emptied sections; updates the count line and empty state.
  // NOTES:  n counts non-duplicate cards only, so the visible total never overcounts.
  function apply() {
    var term = fold(input.value.replace(/^\s+|\s+$/g, ''));
    var filtered = active !== 'all' || term !== '';
    var n = 0;
    items.forEach(function (i) {
      var ok = !(filtered && i.dup)
        && (active === 'all' || i.cat === active)
        && (term === '' || i.text.indexOf(term) > -1);
      i.el.style.display = ok ? '' : 'none';
      if (ok && !i.dup) n++;
    });
    if (latest) latest.style.display = filtered ? 'none' : '';
    if (latestLabel) latestLabel.style.display = filtered ? 'none' : '';
    [].forEach.call(document.querySelectorAll('.b-label[data-sec]'), function (l) {
      var g = document.querySelector('[data-sec-grid="' + l.getAttribute('data-sec') + '"]');
      if (!g) return;
      var any = false;
      [].forEach.call(g.children, function (ch) { if (ch.style.display !== 'none') any = true; });
      l.style.display = any ? '' : 'none';
      g.style.display = any ? '' : 'none';
    });
    if (countEl) {
      if (filtered) {
        var tpl = countEl.getAttribute('data-tpl') || '{n} / {t}';
        countEl.textContent = tpl.replace('{n}', n).replace('{t}', total);
        countEl.hidden = false;
      } else {
        countEl.hidden = true;
      }
    }
    if (emptyEl) emptyEl.style.display = n === 0 ? 'block' : 'none';
  }

  chips.forEach(function (b) {
    b.addEventListener('click', function () {
      active = b.getAttribute('data-filter');
      setChips();
      try {
        var u = new URL(location.href);
        if (active === 'all') u.searchParams.delete('cat');
        else u.searchParams.set('cat', active);
        history.replaceState(null, '', u);
      } catch (e) {}
      apply();
    });
  });
  var deb;
  input.addEventListener('input', function () {
    clearTimeout(deb);
    deb = setTimeout(apply, 150);
  });
  input.addEventListener('search', apply);
  setChips();
  if (active !== 'all') apply();
})();
