/* AUTO-GENERATED */
window.WATCHES_DATA = [
  {
    "id": "watch-1",
    "brand": "Hislon",
    "model": "Classic",
    "reference": "CL213S-02SS",
    "condition": "New",
    "price": 199,
    "currency": "EUR",
    "image": "/images/watches/hislon-cl213s-02ss.webp",
    "sold": false,
    "description_en": "Clean, understated elegance in stainless steel. Fluted bezel, horizontal-stripe silver dial, sapphire crystal, and date window. A reliable everyday dress watch.",
    "description_it": "Eleganza sobria in acciaio inossidabile. Lunetta zigrinata, quadrante argentato a righe orizzontali, cristallo zaffiro e finestrella data. Un orologio da giorno affidabile.",
    "description_sq": "Elegancë e thjeshtë në çelik inox. Bezel i gdhendur, cadran argjendi me vija horizontale, xham safiri dhe dritare date. Orë e besueshme për çdo ditë."
  },
  {
    "id": "watch-2",
    "brand": "Hislon",
    "model": "Classic Queen",
    "reference": "QL145T-09SG",
    "condition": "New",
    "price": 189,
    "currency": "EUR",
    "image": "/images/watches/hislon-ql145t-09sg.webp",
    "sold": false,
    "description_en": "A refined ladies' watch with a rose gold-tone case and bracelet. Slim profile, elegant dial, and reliable quartz movement - effortless everyday style.",
    "description_it": "Orologio da donna raffinato con cassa e bracciale in oro rosa. Profilo sottile, quadrante elegante e movimento al quarzo affidabile.",
    "description_sq": "Orë elegante për femra me kasë dhe byzylyk në ngjyrë ari rozë. Profil i hollë, cadran elegant dhe lëvizje kuarci e besueshme."
  },
  {
    "id": "watch-3",
    "brand": "Hislon",
    "model": "Classic",
    "reference": "CL213G-02SG",
    "condition": "New",
    "price": 189,
    "originalPrice": 209,
    "currency": "EUR",
    "image": "/images/watches/hislon-cl213g-02sg.webp",
    "sold": false,
    "description_en": "The Classic in full gold-tone stainless steel. Fluted bezel, horizontal-stripe silver dial, gold-tone hands and indices, sapphire crystal, and date window.",
    "description_it": "Il Classic in acciaio inossidabile total gold. Lunetta zigrinata, quadrante argentato a righe, lancette e indici dorati, cristallo zaffiro e finestrella data.",
    "description_sq": "Classic-u në çelik inox total gold. Bezel i gdhendur, cadran argjendi me vija, tregues dhe akrepë të artë, xham safiri dhe dritare date."
  },
  {
    "id": "watch-4",
    "brand": "Hislon",
    "model": "Masterwork",
    "reference": "MS201S-04SS",
    "condition": "New",
    "price": 184,
    "currency": "EUR",
    "image": "/images/watches/hislon-ms201s-04ss.webp",
    "sold": false,
    "description_en": "A bold sport-chic chronograph with a jet-black dial, sapphire crystal, and stainless steel bracelet. Three subdials, red accent details, and a date window - precision with attitude.",
    "description_it": "Cronografo sport-chic audace con quadrante nero, cristallo zaffiro e bracciale in acciaio. Tre sotto-quadranti, dettagli rossi e finestrella data - precisione con carattere.",
    "description_sq": "Kronograf sport me cadran të zi, xham safiri dhe byzylyk çeliku. Tre nën-cadranë, detaje të kuqe dhe dritare date - precizion me karakter."
  },
  {
    "id": "watch-5",
    "brand": "Hislon",
    "model": "Classic Queen",
    "reference": "QL113G-09SG",
    "condition": "New",
    "price": 169,
    "currency": "EUR",
    "image": "/images/watches/hislon-ql113g-09sg.webp",
    "sold": false,
    "description_en": "A ladies' classic in full gold-tone steel with a mother-of-pearl dial set with crystal indices, sapphire crystal, blue hands, and a date window. Timeless femininity.",
    "description_it": "Orologio da donna classico in acciaio dorato con quadrante madreperla, indici con cristalli, cristallo zaffiro, lancette blu e finestrella data. Femminilità senza tempo.",
    "description_sq": "Orë klasike për femra në çelik të artë me cadran sedef, tregues me kristale, xham safiri, akrepë blu dhe dritare date. Femërorësi pa kohë."
  },
  {
    "id": "watch-6",
    "brand": "Hislon",
    "model": "Women Classic Queen",
    "reference": "QL113-09SS",
    "condition": "New",
    "price": 149,
    "currency": "EUR",
    "image": "/images/watches/hislon-ql113g-09ss.webp",
    "sold": false,
    "description_en": "The Women Classic Queen in stainless steel with a mother-of-pearl dial, crystal indices, sapphire crystal, blue hands, and a date window. Understated elegance for every day.",
    "description_it": "La Women Classic Queen in acciaio inossidabile con quadrante madreperla, indici con cristalli, cristallo zaffiro, lancette blu e finestrella data. Eleganza sobria per ogni giorno.",
    "description_sq": "Women Classic Queen në çelik inox me cadran sedef, tregues me kristale, xham safiri, akrepë blu dhe dritare date. Elegancë e thjeshtë për çdo ditë."
  },
  {
    "id": "watch-7",
    "brand": "Navimarine",
    "model": "NM268-06",
    "reference": "NM268-06",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm268-06.webp",
    "sold": false,
    "description_en": "A sport-inspired marine watch with a bold, clean dial and sturdy stainless steel case. Reliable quartz movement, date window, and a versatile strap - ready for both sea and city.",
    "description_it": "Un orologio marino dallo stile sportivo con quadrante pulito e cassa robusta in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino versatile - pronto per il mare e la citta.",
    "description_sq": "Ore marine me stil sportiv, cadran te paster dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i gjithanshme - gati per det dhe qytet."
  },
  {
    "id": "watch-8",
    "brand": "Hislon",
    "model": "Classic",
    "reference": "CL214S-04SS",
    "condition": "New",
    "price": 199,
    "currency": "EUR",
    "image": "/images/watches/hislon-cl214s-04ss.webp",
    "sold": false,
    "description_en": "The Classic CL214S-04SS in two-tone stainless steel - silver case with gold-tone accents. Fluted bezel, clean silver dial with gold-tone hands and indices, sapphire crystal, and date window. Timeless dress elegance at its finest.",
    "description_it": "Il Classic CL214S-04SS in acciaio inossidabile bicolore - cassa argentata con dettagli dorati. Lunetta zigrinata, quadrante argentato con lancette e indici dorati, cristallo zaffiro e finestrella data. Eleganza senza tempo.",
    "description_sq": "Classic CL214S-04SS ne celiku inox dy-tone - kase argjendi me detaje te arta. Bezel i gdhendur, cadran argjendi me akrape dhe tregues te arte, xham safiri dhe dritare date. Elegance klasike ne kulmin e saj."
  },
  {
    "id": "watch-9",
    "brand": "Navimarine",
    "model": "NMM1011",
    "reference": "NMM1011",
    "condition": "New",
    "price": 60,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nmm1011.webp",
    "sold": false,
    "description_en": "A bold marine timepiece with a striking multi-layered dial and robust stainless steel case. Reliable quartz movement, luminous hands, and a durable strap - built for adventure on and off the water.",
    "description_it": "Un orologio marino deciso con quadrante multistrato dal carattere forte e cassa robusta in acciaio inossidabile. Movimento al quarzo affidabile, lancette luminose e cinturino resistente - fatto per l'avventura in mare e in citta.",
    "description_sq": "Ore marine me cadran shume-shtresor me karakter te forte dhe kase te forte celiku inox. Levizje kuarci e besueshme, akrape ndriçuese dhe rrip i qendrueshem - krijuar per aventura ne det dhe ne qytet."
  },
  {
    "id": "watch-10",
    "brand": "Navimarine",
    "model": "NM232-04",
    "reference": "NM232-04",
    "condition": "New",
    "price": 65,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm232-04.webp",
    "sold": false,
    "description_en": "A clean, sporty marine watch with a crisp dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - understated style for everyday wear.",
    "description_it": "Un orologio marino dallo stile sportivo e pulito con quadrante nitido e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - stile sobrio per ogni giorno.",
    "description_sq": "Ore marine me stil sportiv dhe te paster, cadran te qarte dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - elegance e qete per cdo dite."
  },
  {
    "id": "watch-11",
    "brand": "Navimarine",
    "model": "NAVI 009-COL 6",
    "reference": "NAVI-009-COL6",
    "condition": "New",
    "price": 95,
    "currency": "EUR",
    "image": "/images/watches/navimarine-navi-009-col6.webp",
    "sold": false,
    "description_en": "A vibrant sport marine watch with a colourful dial and durable stainless steel case. Reliable quartz movement, date window, and a comfortable strap - bold style for everyday adventures.",
    "description_it": "Un orologio marino sportivo con quadrante colorato e cassa resistente in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - stile deciso per le avventure di tutti i giorni.",
    "description_sq": "Ore marine sportive me cadran me ngjyra dhe kase te qendrueshem celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - stil i guximshem per aventurat e perditshme."
  },
  {
    "id": "watch-12",
    "brand": "Navimarine",
    "model": "NVM141-A1",
    "reference": "NVM141-A1",
    "condition": "New",
    "price": 65,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nvm141-a1.webp",
    "sold": false,
    "description_en": "A sleek marine watch with a refined dial and lightweight stainless steel case. Reliable quartz movement, date window, and a supple strap - effortless style for sea and everyday wear.",
    "description_it": "Un orologio marino elegante con quadrante curato e cassa leggera in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino morbido - stile senza sforzo per il mare e il quotidiano.",
    "description_sq": "Ore marine elegante me cadran te rafinuar dhe kase te lehte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i bute - stil pa mundim per detin dhe perditshmerin."
  },
  {
    "id": "watch-13",
    "brand": "Navimarine",
    "model": "NM181-03",
    "reference": "NM181-03",
    "condition": "New",
    "price": 70,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm181-03.webp",
    "sold": false,
    "description_en": "A refined marine watch with a clean dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - quiet confidence for every occasion.",
    "description_it": "Un orologio marino raffinato con quadrante pulito e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - stile discreto per ogni occasione.",
    "description_sq": "Ore marine e rafinuar me cadran te paster dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - elegance e qete per cdo rast."
  },
  {
    "id": "watch-14",
    "brand": "Navimarine",
    "model": "NT0029-2",
    "reference": "NT0029-2",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nt0029-2.webp",
    "sold": false,
    "description_en": "A bold sport watch with a striking dial and robust stainless steel case. Reliable quartz movement, date window, and a sturdy strap - strong character for active everyday wear.",
    "description_it": "Un orologio sportivo deciso con quadrante dal carattere forte e cassa robusta in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino resistente - stile energico per ogni giorno attivo.",
    "description_sq": "Ore sportive me cadran te fuqishem dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i forte - karakter i gjalle per cdo dite aktive."
  },
  {
    "id": "watch-15",
    "brand": "Navimarine",
    "model": "NM282-04",
    "reference": "NM282-04",
    "condition": "New",
    "price": 65,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm282-04.webp",
    "sold": false,
    "description_en": "A classic marine watch with a well-balanced dial and reliable stainless steel case. Precise quartz movement, date window, and a comfortable strap - timeless style that fits any wrist and any occasion.",
    "description_it": "Un orologio marino classico con quadrante equilibrato e cassa affidabile in acciaio inossidabile. Movimento al quarzo preciso, finestrella data e cinturino comodo - stile senza tempo per ogni polso e ogni occasione.",
    "description_sq": "Ore marine klasike me cadran te balancuar dhe kase te besueshme celiku inox. Levizje kuarci precize, dritare date dhe rrip i rehatshme - stil i perjeteshem per cdo dore dhe cdo rast."
  },
  {
    "id": "watch-16",
    "brand": "Navimarine",
    "model": "NVM112-B4",
    "reference": "NVM112-B4",
    "condition": "New",
    "price": 70,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nvm112-b4.webp",
    "sold": false,
    "description_en": "A sharp marine watch with a distinctive dial design and sturdy stainless steel case. Reliable quartz movement, date window, and a comfortable strap - a confident choice for sea and city alike.",
    "description_it": "Un orologio marino dal design distintivo con cassa robusta in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - una scelta decisa per il mare e la citta.",
    "description_sq": "Ore marine me dizajn te vecante dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - zgjedhje e sigurt per detin dhe qytetin."
  },
  {
    "id": "watch-17",
    "brand": "Navimarine",
    "model": "NAVI 009-COL 1",
    "reference": "NAVI-009-COL1",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-navi-009-col1.webp",
    "sold": false,
    "description_en": "A vibrant marine watch from the NAVI 009 collection with a bold colourful dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - made to stand out on land and at sea.",
    "description_it": "Un orologio marino vivace della collezione NAVI 009 con quadrante colorato e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - fatto per distinguersi a terra e in mare.",
    "description_sq": "Ore marine e gjalle nga koleksioni NAVI 009 me cadran me ngjyra dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - krijuar per t'u dalluar ne toke dhe ne det."
  },
  {
    "id": "watch-18",
    "brand": "Navimarine",
    "model": "NM001101-color06",
    "reference": "NM001101-COL06",
    "condition": "New",
    "price": 65,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm001101-col06.webp",
    "sold": false,
    "description_en": "A lively marine watch with a colourful dial and dependable stainless steel case. Reliable quartz movement, date window, and a flexible strap - casual style with a maritime spirit.",
    "description_it": "Un orologio marino vivace con quadrante colorato e cassa affidabile in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino flessibile - stile casual con spirito marinaro.",
    "description_sq": "Ore marine e gjalle me cadran me ngjyra dhe kase te besueshme celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip fleksibel - stil i lire me fryme detare."
  },
  {
    "id": "watch-19",
    "brand": "Navimarine",
    "model": "NT0031-1",
    "reference": "NT0031-1",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nt0031-1.webp",
    "sold": false,
    "description_en": "A robust sport marine watch with a bold dial and solid stainless steel case. Reliable quartz movement, date window, and a durable strap - built for those who wear their watches hard.",
    "description_it": "Un orologio marino sportivo e robusto con quadrante deciso e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino resistente - fatto per chi indossa l'orologio senza risparmiarsi.",
    "description_sq": "Ore marine sportive dhe e forte me cadran te fuqishem dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i qendrueshem - bere per ata qe e veshin oren pa kursim."
  },
  {
    "id": "watch-20",
    "brand": "Navimarine",
    "model": "NM001404-Color04",
    "reference": "NM001404-COL04",
    "condition": "New",
    "price": 75,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm001404-col04-removebg-preview.webp",
    "sold": false,
    "description_en": "A eye-catching marine watch with a colourful dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - expressive style for everyday adventures.",
    "description_it": "Un orologio marino dal quadrante colorato e dalla cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - stile espressivo per le avventure di tutti i giorni.",
    "description_sq": "Ore marine me cadran me ngjyra dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - stil shprehes per aventurat e perditshme."
  },
  {
    "id": "watch-21",
    "brand": "Navimarine",
    "model": "001808-color02",
    "reference": "001808-COL02",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-001808-col02.webp",
    "sold": false,
    "description_en": "A striking marine watch with a vivid coloured dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - bold personality for every day on and off the water.",
    "description_it": "Un orologio marino dal quadrante colorato vivace e dalla cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - personalita decisa per ogni giorno in mare e a terra.",
    "description_sq": "Ore marine me cadran me ngjyra te gjalla dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - personalitet i guximshem per cdo dite ne det dhe ne toke."
  },
  {
    "id": "watch-22",
    "brand": "Navimarine",
    "model": "NM229-06",
    "reference": "NM229-06",
    "condition": "New",
    "price": 75,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm229-06.webp",
    "sold": false,
    "description_en": "A sleek marine watch with a clean dial and dependable stainless steel case. Reliable quartz movement, date window, and a comfortable strap - understated maritime style for every occasion.",
    "description_it": "Un orologio marino elegante con quadrante pulito e cassa affidabile in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - stile marinaro sobrio per ogni occasione.",
    "description_sq": "Ore marine elegante me cadran te paster dhe kase te besueshme celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - stil detar i qete per cdo rast."
  },
  {
    "id": "watch-23",
    "brand": "Navimarine",
    "model": "NVM180-A2",
    "reference": "NVM180-A2",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nvm180-a2.webp",
    "sold": false,
    "description_en": "A refined marine watch with a well-composed dial and solid stainless steel case. Reliable quartz movement, date window, and a supple strap - polished maritime style worn with ease every day.",
    "description_it": "Un orologio marino raffinato con quadrante ben composto e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino morbido - stile marinaro curato, da indossare con disinvoltura ogni giorno.",
    "description_sq": "Ore marine e rafinuar me cadran te kompozuar mire dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i bute - stil detar i leshuar, i veshur me lehtesi cdo dite."
  },
  {
    "id": "watch-24",
    "brand": "Navimarine",
    "model": "NM001101-Color02",
    "reference": "NM001101-COL02",
    "condition": "New",
    "price": 65,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm001101-col02.webp",
    "sold": false,
    "description_en": "A fresh take on the NM001101 with a distinctive colour two dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - casual maritime character for everyday wear.",
    "description_it": "Una nuova interpretazione dell'NM001101 con quadrante nel colore due distintivo e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - carattere marinaro casual per ogni giorno.",
    "description_sq": "Nje interpretim i ri i NM001101 me cadran ne ngjyren e dyte dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - karakter detar i lire per cdo dite."
  },
  {
    "id": "watch-25",
    "brand": "Navimarine",
    "model": "NMM1013",
    "reference": "NMM1013",
    "condition": "New",
    "price": 85,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nmm1013.webp",
    "sold": false,
    "description_en": "A bold marine sport watch with a commanding dial and sturdy stainless steel case. Reliable quartz movement, date window, and a durable strap - strong presence for active wear on and off the water.",
    "description_it": "Un orologio marino sportivo dal quadrante imponente e dalla cassa robusta in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino resistente - presenza forte per chi non si ferma mai.",
    "description_sq": "Ore marine sportive me cadran imponues dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i qendrueshem - prezence e forte per veshje aktive ne det dhe ne toke."
  },
  {
    "id": "watch-26",
    "brand": "Navimarine",
    "model": "NM182-01",
    "reference": "NM182-01",
    "condition": "New",
    "price": 70,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nm182-01.webp",
    "sold": false,
    "description_en": "A clean and confident marine watch with a well-balanced dial and solid stainless steel case. Reliable quartz movement, date window, and a comfortable strap - timeless style that works from the dock to the office.",
    "description_it": "Un orologio marino pulito e deciso con quadrante equilibrato e cassa solida in acciaio inossidabile. Movimento al quarzo affidabile, finestrella data e cinturino comodo - stile senza tempo dal molo all'ufficio.",
    "description_sq": "Ore marine e paster dhe e sigurt me cadran te balancuar dhe kase te forte celiku inox. Levizje kuarci e besueshme, dritare date dhe rrip i rehatshme - stil i perjeteshem nga skelat deri ne zyre."
  },
  {
    "id": "watch-27",
    "brand": "Navimarine",
    "model": "NT0021-1",
    "reference": "NT0021-1",
    "condition": "New",
    "price": 75,
    "currency": "EUR",
    "image": "/images/watches/navimarine-nt0021-1.webp",
    "sold": false,
    "description_en": "Classic Navimarine NT0021-1 quartz watch with a timeless design. Features a clean dial, durable case, and comfortable strap - a reliable everyday timepiece at an excellent value.",
    "description_it": "Orologio al quarzo Navimarine NT0021-1 dal design senza tempo. Quadrante pulito, cassa robusta e cinturino comodo - un segnatempo affidabile di ottimo valore.",
    "description_sq": "Orë kuarci klasike Navimarine NT0021-1 me dizajn të përjetshëm. Ciferblat i pastër, kallëp i qëndrueshëm dhe rrip i rehatshëm - një orë e besueshme e përditshme me vlerë të shkëlqyer."
  },
  {
    "id": "watch-28",
    "brand": "Navimarine",
    "model": "NM001404-Color01",
    "reference": "NM001404-Color01",
    "condition": "New",
    "price": 90,
    "currency": "EUR",
    "image": "/images/watches/NAVIMARINE_NM001404-color01-removebg-preview.webp",
    "sold": false,
    "description_en": "Elegant Navimarine NM001404-Color01 with a refined dial and premium finish. A stylish quartz timepiece that combines classic proportions with everyday reliability.",
    "description_it": "Elegante Navimarine NM001404-Color01 con quadrante raffinato e finitura premium. Un orologio al quarzo che unisce proporzioni classiche e affidabilità quotidiana.",
    "description_sq": "Navimarine NM001404-Color01 elegante me ciferblat të rafinuar dhe mbarim premium. Orë kuarci elegante që kombinon proporcionet klasike me besueshmërinë e përditshme."
  },
  {
    "id": "citizen-quartz-gn",
    "brand": "Citizen",
    "model": "Quartz GN",
    "reference": "",
    "condition": "New",
    "price": 60,
    "currency": "EUR",
    "image": "/images/watches/citizen-quartz-gn.webp",
    "sold": false,
    "description_en": "Citizen Japanese quartz with mineral glass crystal and gold-plated stainless steel case and bracelet. Clean dial, reliable movement, and an elegant golden finish from every angle.",
    "description_it": "Quarzo giapponese Citizen con vetro minerale e cassa in acciaio inossidabile placcata oro. Quadrante pulito, movimento affidabile e finitura dorata elegante da ogni angolazione.",
    "description_sq": "Kuarc japonez Citizen me xham mineral dhe kuti çeliku inox me veshje ari. Ciferblat i pastër, lëvizje e besueshme dhe finiturë elegante ari nga çdo kënd."
  },
  {
    "id": "casio-mtp-vd01",
    "brand": "Casio",
    "model": "MTP-VD01",
    "reference": "MTP-VD01D-1EVUDF",
    "condition": "New",
    "price": 52,
    "currency": "EUR",
    "image": "/images/watches/casio-mtp-vd01.webp",
    "sold": false,
    "description_en": "Bold stainless steel sports-dress watch by Casio. Black dial with luminous baton indices, date window at 3 o'clock, 50m water resistance, and reliable Japanese quartz movement. Sharp enough for the office, tough enough for everyday wear.",
    "description_it": "Orologio Casio in acciaio inossidabile dal carattere sportivo ed elegante. Quadrante nero con indici a bastone luminosi, finestrella data alle 3, resistenza all'acqua 50m e preciso movimento al quarzo giapponese. Adatto all'ufficio come all'uso quotidiano.",
    "description_sq": "Orë sportive-elegante Casio në çelik inox. Cadran i zi me indikatorë bastun luminozë, fenestrë date në pozicionin 3, rezistencë ndaj ujit 50m dhe lëvizje kuarci japoneze e besueshme. Elegante për zyrën, e qëndrueshme për çdo ditë."
  },
  {
    "id": "bigotti-bg1-10154-1",
    "brand": "Bigotti",
    "model": "BG1.10154.1",
    "reference": "BG1.10154.1",
    "condition": "New",
    "price": 84,
    "currency": "EUR",
    "image": "/images/watches/bigotti-bg1-10154-1.webp",
    "sold": false,
    "description_en": "Bigotti BG1.10154.1 - stainless steel multi-function watch with a white dial, day-date display, and multiple subdials. Clean baton indices, three-pusher chronograph case, and brushed steel bracelet. A sharp, functional timepiece at an excellent price.",
    "description_it": "Bigotti BG1.10154.1 - orologio multifunzione in acciaio inossidabile con quadrante bianco, display giorno-data e più contatori. Indici a bastone puliti, cassa con tre pulsanti e bracciale in acciaio spazzolato. Un orologio preciso e funzionale a un ottimo prezzo.",
    "description_sq": "Bigotti BG1.10154.1 - orë multifunksionale çeliku inox me ciferblat të bardhë, tregues dite-date dhe nën-cadranë të shumtë. Indikatorë bastun të pastër, kuti me tre butona dhe byzylyk çeliku të brushuar. Orë precize dhe funksionale me çmim të shkëlqyer."
  },
  {
    "id": "navimarine-steel-5atm-blue",
    "brand": "Navimarine",
    "model": "Steel 5ATM Blue",
    "reference": "NT0022-1",
    "condition": "New",
    "price": 75,
    "currency": "EUR",
    "image": "/images/watches/navimarine-steel-5atm-blue.webp",
    "sold": false,
    "description_en": "Navimarine Steel 5ATM - classic stainless steel watch with a deep blue sunburst dial and Roman numeral hour markers. Date display at 3 o'clock, 5 ATM water resistance, and a solid brushed steel bracelet. A confident, elegant everyday watch.",
    "description_it": "Navimarine Steel 5ATM - orologio classico in acciaio inossidabile con quadrante blu sunburst e numeri romani. Data alle 3, resistenza all'acqua 5 ATM e bracciale in acciaio spazzolato solido. Un orologio quotidiano elegante e deciso.",
    "description_sq": "Navimarine Steel 5ATM - orë klasike çeliku inox me ciferblat blu sunburst dhe tregues numrash romakë. Datë në pozicionin 3, rezistencë ndaj ujit 5 ATM dhe byzylyk çeliku solid të brushuar. Orë e përditshme elegante dhe e sigurt."
  },
  {
    "id": "belonni-collection",
    "brand": "Belonni",
    "model": "Collection",
    "reference": "",
    "condition": "New",
    "price": 50,
    "currency": "EUR",
    "image": "/images/watches/belonni-collection.webp",
    "sold": false,
    "description_en": "Belonni Collection all-stainless-steel watch with a clean white dial, Arabic numeral markers, date display at 3, and a fluted coin-edge bezel. 3 ATM water resistant with a five-link Jubilee-style bracelet.",
    "description_it": "Belonni Collection in acciaio inossidabile con quadrante bianco pulito, indicatori numerici arabi, data alle 3 e ghiera a bordo moneta. Resistente all'acqua 3 ATM con bracciale a cinque maglie stile Jubilee.",
    "description_sq": "Belonni Collection çelik inox me ciferblat të bardhë, tregues numrash arabë, datë në pozicionin 3 dhe unazë me skaj monedhe. Rezistente ndaj ujit 3 ATM me byzylyk me pesë hallka stil Jubilee."
  },
  {
    "id": "romanson-bh3054gbr",
    "brand": "Romanson",
    "model": "BH3054GBR",
    "reference": "BH3054GBR",
    "condition": "New",
    "price": 74,
    "currency": "EUR",
    "image": "/images/watches/romanson-bh3054gbr.webp",
    "sold": false,
    "description_en": "Romanson Parie Swiss quartz with sapphire crystal glass and full gold-plated case and bracelet. Elegant rectangular case with sunburst dial, dot and bar markers, date display, and Swiss-made precision.",
    "description_it": "Quarzo svizzero Romanson Parie con vetro in zaffiro e cassa e bracciale interamente placcati oro. Cassa rettangolare elegante con quadrante sunburst, indicatori a punti e barre, data e precisione svizzera.",
    "description_sq": "Kuarc zviceran Romanson Parie me xham safir dhe kuti dhe byzylyk plotësisht të artë. Kuti drejtkëndëshe elegante me ciferblat sunburst, tregues pikash dhe shiritash, datë dhe precizion zviceran."
  },
  {
    "id": "daniel-klein-premium",
    "brand": "Daniel Klein",
    "model": "Premium",
    "reference": "DK.1.12971-2",
    "condition": "New",
    "price": 64,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-premium.webp",
    "sold": false,
    "description_en": "Daniel Klein Premium gold-plated watch with a silver sunburst dial, applied gold bar indices, and a fluted coin-edge bezel. Date display at 3, Roman numeral chapter ring, and a three-link gold-tone bracelet. Classic elegance with a bold Datejust-inspired profile.",
    "description_it": "Orologio Daniel Klein Premium placcato oro con quadrante sunburst argento, indici a barra applicati dorati e ghiera zigrinata a bordo moneta. Data alle 3, anello delle ore con numeri romani e bracciale a tre maglie in color oro. Eleganza classica con un profilo audace ispirato al Datejust.",
    "description_sq": "Orë Daniel Klein Premium me veshje ari me ciferblat sunburst argjendi, tregues shiritash të aplikuar artë dhe unazë me skaj të gdhendur. Datë në pozicionin 3, unazë orësh me numra romakë dhe byzylyk me tre hallka në ngjyrë ari. Elegancë klasike me profil të guximshëm."
  },
  {
    "id": "daniel-klein-mesh",
    "brand": "Daniel Klein",
    "model": "Mesh",
    "reference": "",
    "condition": "New",
    "price": 60,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-mesh.webp",
    "sold": false,
    "description_en": "Daniel Klein Mesh minimalist watch with a clean white dial, applied gold bar indices, and a slim gold-plated case. The woven Milanese mesh bracelet in gold-tone adds a refined finish. Simple, elegant, and effortlessly stylish.",
    "description_it": "Orologio minimalista Daniel Klein Mesh con quadrante bianco pulito, indici a barra applicati dorati e cassa sottile placcata oro. Il bracciale a maglia milanese in color oro aggiunge una finitura raffinata. Semplice, elegante e di stile senza sforzo.",
    "description_sq": "Orë minimaliste Daniel Klein Mesh me ciferblat të bardhë të pastër, tregues shiritash të aplikuar artë dhe kuti të hollë me veshje ari. Byzylyk milanez i endur në ngjyrë ari shton një finiturë elegante. E thjeshtë, elegante dhe me stil."
  },
  {
    "id": "daniel-klein-blue",
    "brand": "Daniel Klein",
    "model": "Blue",
    "reference": "DK 1.12576.2",
    "condition": "New",
    "price": 64,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-blue.webp",
    "sold": false,
    "description_en": "Daniel Klein stainless steel watch with a deep blue gradient sunburst dial, coin-edge bezel, and red seconds hand. Date display at 3, applied bar and dot markers, and a solid steel bracelet. A bold everyday watch with a sporty edge.",
    "description_it": "Orologio Daniel Klein in acciaio inossidabile con quadrante blu sfumato sunburst, ghiera a bordo moneta e lancetta dei secondi rossa. Data alle 3, indicatori applicati a barre e punti e bracciale in acciaio solido. Un orologio quotidiano audace con un tocco sportivo.",
    "description_sq": "Orë Daniel Klein çelik inox me ciferblat blu gradient sunburst, unazë me skaj monedhe dhe akrep sekondash të kuq. Datë në pozicionin 3, tregues të aplikuar shiritash dhe pikash dhe byzylyk i fortë çeliku. Një orë e guximshme për çdo ditë me karakter sportiv."
  },
  {
    "id": "daniel-klein-f",
    "brand": "Daniel Klein",
    "model": "F",
    "reference": "",
    "condition": "New",
    "price": 60,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-f.webp",
    "sold": false,
    "description_en": "Daniel Klein women's watch with a slim stainless steel case, a soft white sunburst dial, and rose gold-tone stick indices and hands. A polished bracelet and clean minimalist face make it an elegant everyday piece for any occasion.",
    "description_it": "Orologio da donna Daniel Klein con cassa sottile in acciaio inossidabile, quadrante bianco sunburst delicato e indici e lancette in color oro rosa. Il bracciale lucido e il quadrante minimalista lo rendono un pezzo elegante per ogni occasione.",
    "description_sq": "Orë Daniel Klein për femra me kasë të hollë prej çeliku inox, ciferblat të bardhë sunburst dhe tregues e akrepë në ngjyrë ari rozë. Byzylyku i lëmuar dhe ciferblati minimalist e bëjnë një copë elegante për çdo rast."
  },
  {
    "id": "starking-bm-664",
    "brand": "Starking",
    "model": "Classic Gold",
    "reference": "BM-664",
    "condition": "New",
    "price": 74,
    "currency": "EUR",
    "image": "/images/watches/starking-bm-664.webp",
    "sold": false,
    "description_en": "Starking men's gold-tone dress watch with a tonneau-shaped case, a textured champagne dial, and crystal-set hour accents. Date display at 6, a slim quartz movement, and a polished gold-plated bracelet. Refined elegance for formal occasions.",
    "description_it": "Orologio elegante da uomo Starking in color oro con cassa a forma di tonneau, quadrante champagne testurizzato e accenti alle ore con cristalli. Data alle 6, movimento al quarzo sottile e bracciale placcato oro lucido. Eleganza raffinata per le occasioni formali.",
    "description_sq": "Orë elegante Starking për burra në ngjyrë ari me kasë tonneau, ciferblat champagne të teksturuar dhe detaje me kristale te orët. Datë në pozicionin 6, mekanizëm kuarci i hollë dhe byzylyk i praruar me ar. Elegancë e rafinuar për raste formale."
  },
  {
    "id": "casio-mtp-b145d",
    "brand": "Casio",
    "model": "MTP-B145D",
    "reference": "MTP-B145D-3AVDF",
    "condition": "New",
    "price": 89,
    "currency": "EUR",
    "image": "/images/watches/casio-mtp-b145d.webp",
    "sold": false,
    "description_en": "Casio stainless steel watch with a striking green sunburst dial, faceted bezel, and integrated steel bracelet. Luminous baton indices, date window at 3, and 50m water resistance, powered by a reliable Japanese quartz movement. A sharp modern-retro everyday watch.",
    "description_it": "Orologio Casio in acciaio inossidabile con quadrante verde sunburst, lunetta sfaccettata e bracciale integrato in acciaio. Indici a bastone luminosi, finestrella data alle 3 e resistenza all'acqua 50m, con affidabile movimento al quarzo giapponese. Un orologio moderno-retrò per ogni giorno.",
    "description_sq": "Orë Casio në çelik inox me ciferblat jeshil sunburst, bezel të fasetuar dhe byzylyk të integruar çeliku. Tregues bastun luminozë, dritare date në pozicionin 3 dhe rezistencë ndaj ujit 50m, me lëvizje kuarci japoneze të besueshme. Një orë moderne-retro për çdo ditë."
  },
  {
    "id": "philippe-lauren-pl2427-1",
    "brand": "Philippe Lauren",
    "model": "Silver Chronograph",
    "reference": "PL2427-1",
    "condition": "New",
    "price": 72,
    "currency": "EUR",
    "image": "/images/watches/philippe-lauren-pl2427-1.webp",
    "sold": false,
    "description_en": "Philippe Lauren men's chronograph with a cushion-shaped stainless steel case, a silver sunburst dial, and three chronograph sub-dials. Date window, applied indices, and a polished steel bracelet. A refined dress chronograph with a distinctive tonneau profile.",
    "description_it": "Cronografo da uomo Philippe Lauren con cassa in acciaio inossidabile a forma di cuscino, quadrante argento sunburst e tre contatori cronografici. Finestrella data, indici applicati e bracciale in acciaio lucido. Un cronografo elegante dal profilo tonneau distintivo.",
    "description_sq": "Kronograf për burra Philippe Lauren me kasë prej çeliku inox në formë jastëku, ciferblat argjendi sunburst dhe tre nën-ciferblatë kronografi. Dritare date, tregues të aplikuar dhe byzylyk çeliku i lëmuar. Një kronograf elegant me profil tonneau dallues."
  },
  {
    "id": "philippe-lauren-pl2435-5",
    "brand": "Philippe Lauren",
    "model": "Black Chronograph",
    "reference": "PL2435-5",
    "condition": "New",
    "price": 72,
    "currency": "EUR",
    "image": "/images/watches/philippe-lauren-pl2435-5.webp",
    "sold": false,
    "description_en": "Philippe Lauren men's chronograph in black ion-plated stainless steel, with a black dial, three chronograph sub-dials, and luminous applied indices. Date window and a matching black steel bracelet. A bold, all-black sport-dress chronograph.",
    "description_it": "Cronografo da uomo Philippe Lauren in acciaio inossidabile placcato nero, con quadrante nero, tre contatori cronografici e indici applicati luminosi. Finestrella data e bracciale in acciaio nero abbinato. Un cronografo sport-elegante total black e deciso.",
    "description_sq": "Kronograf për burra Philippe Lauren në çelik inox të veshur me jon të zi, me ciferblat të zi, tre nën-ciferblatë kronografi dhe tregues të aplikuar luminozë. Dritare date dhe byzylyk çeliku i zi i përshtatur. Një kronograf sportiv-elegant tërësisht i zi dhe i guximshëm."
  },
  {
    "id": "philippe-lauren-pl2435-2",
    "brand": "Philippe Lauren",
    "model": "Steel Chronograph",
    "reference": "PL2435-2",
    "condition": "New",
    "price": 72,
    "currency": "EUR",
    "image": "/images/watches/philippe-lauren-pl2435-2.webp",
    "sold": false,
    "description_en": "Philippe Lauren men's chronograph in polished stainless steel with a black dial, three chronograph sub-dials, and luminous applied indices. Date window, a round case, and a solid steel bracelet. A versatile sport-dress chronograph that pairs with anything.",
    "description_it": "Cronografo da uomo Philippe Lauren in acciaio inossidabile lucido con quadrante nero, tre contatori cronografici e indici applicati luminosi. Finestrella data, cassa rotonda e bracciale in acciaio massiccio. Un cronografo sport-elegante versatile, abbinabile a tutto.",
    "description_sq": "Kronograf për burra Philippe Lauren në çelik inox të lëmuar me ciferblat të zi, tre nën-ciferblatë kronografi dhe tregues të aplikuar luminozë. Dritare date, kasë rrumbullake dhe byzylyk çeliku i fortë. Një kronograf sportiv-elegant i gjithanshëm, që shkon me gjithçka."
  },
  {
    "id": "casio-a159wa",
    "brand": "Casio",
    "model": "A159WA",
    "reference": "A159WA-N1",
    "condition": "New",
    "price": 61,
    "currency": "EUR",
    "image": "/images/watches/casio-a159wa.webp",
    "sold": false,
    "description_en": "The legendary Casio A159WA-N1 retro digital, essentially unchanged since the early 1980s. Stainless steel case and bracelet, black bezel, LCD with alarm, stopwatch, day and date, LED light, and water resistance. An icon of everyday reliability weighing next to nothing.",
    "description_it": "Il leggendario Casio A159WA-N1 digitale rétro, praticamente immutato dai primi anni '80. Cassa e bracciale in acciaio inossidabile, ghiera nera, LCD con sveglia, cronometro, giorno e data, luce LED e resistenza all'acqua. Un'icona di affidabilità quotidiana dal peso piuma.",
    "description_sq": "Casio A159WA-N1 legjendar dixhital retro, praktikisht i pandryshuar që nga fillimi i viteve '80. Kasë dhe byzylyk çeliku inox, unazë e zezë, LCD me alarm, kronometër, ditë e datë, dritë LED dhe rezistencë ndaj ujit. Një ikonë e besueshmërisë së përditshme me peshë pendë."
  },
  {
    "id": "casio-w-737hx",
    "brand": "Casio",
    "model": "W-737HX",
    "reference": "W-737HX-1AVDF",
    "condition": "New",
    "price": 67,
    "currency": "EUR",
    "image": "/images/watches/casio-w-737hx.webp",
    "sold": false,
    "description_en": "Bold black resin sport watch by Casio with gold Illuminator accents. Large positive LCD with day, date and seconds, 100m water resistance, LED backlight, alarm, stopwatch and countdown timer, all on a 10-year battery. Tough, legible and built for everyday wear.",
    "description_it": "Robusto orologio sportivo Casio in resina nera con dettagli dorati Illuminator. Ampio display LCD positivo con giorno, data e secondi, resistenza all'acqua 100m, retroilluminazione LED, sveglia, cronometro e timer con conto alla rovescia, il tutto con batteria a 10 anni. Resistente, leggibile e pronto all'uso quotidiano.",
    "description_sq": "Orë sportive e fortë Casio në rezinë të zezë me detaje të arta Illuminator. Ekran i madh LCD pozitiv me ditë, datë dhe sekonda, rezistencë ndaj ujit 100m, ndriçim LED, alarm, kronometër dhe timer numërimi mbrapsht, të gjitha me bateri 10-vjeçare. E fortë, e lexueshme dhe e bërë për përdorim të përditshëm."
  },
  {
    "id": "casio-ae-1500wh",
    "brand": "Casio",
    "model": "AE-1500WH",
    "reference": "AE-1500WH-8BVDF",
    "condition": "New",
    "price": 67,
    "currency": "EUR",
    "image": "/images/watches/casio-ae-1500wh.webp",
    "sold": false,
    "description_en": "All-black digital sport watch by Casio with a stealth negative display. Large round resin case, 100m water resistance, LED Illuminator backlight, 5 daily alarms, stopwatch and countdown timer, all on a 10-year battery. A big, easy-to-read everyday watch with a blacked-out look.",
    "description_it": "Orologio sportivo digitale Casio tutto nero con display negativo dallo stile stealth. Ampia cassa rotonda in resina, resistenza all'acqua 100m, retroilluminazione LED Illuminator, 5 sveglie giornaliere, cronometro e timer con conto alla rovescia, il tutto con batteria a 10 anni. Un orologio quotidiano grande e facile da leggere dal look total black.",
    "description_sq": "Orë sportive dixhitale Casio krejt e zezë me ekran negativ me pamje stealth. Kasë e madhe rrethore prej rezine, rezistencë ndaj ujit 100m, ndriçim LED Illuminator, 5 alarme ditore, kronometër dhe timer numërimi mbrapsht, të gjitha me bateri 10-vjeçare. Një orë e përditshme e madhe dhe e lehtë për t'u lexuar me pamje krejt të zezë."
  },
  {
    "id": "daniel-klein-14173",
    "brand": "Daniel Klein",
    "model": "Premium Roman",
    "reference": "DK.1.14173-1",
    "condition": "New",
    "price": 69,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-14173.webp",
    "sold": false,
    "description_en": "Elegant Daniel Klein Premium dress watch in polished stainless steel. Cream dial with black Roman numerals, blued hands and a small date window, on a solid five-link steel bracelet. A refined, timeless quartz piece that suits a slimmer wrist and makes an easy gift.",
    "description_it": "Elegante orologio da abito Daniel Klein Premium in acciaio inossidabile lucido. Quadrante crema con numeri romani neri, lancette azzurrate e piccola finestrella data, su un solido bracciale in acciaio a cinque maglie. Un pezzo al quarzo raffinato e senza tempo, adatto a un polso sottile e ideale come regalo.",
    "description_sq": "Orë elegante veshjeje Daniel Klein Premium në çelik inoks të lëmuar. Cadran krem me numra romakë të zinj, akrepa të kaltëruar dhe një dritare të vogël date, mbi një byzylyk solid çeliku me pesë hallka. Një copë kuarci e rafinuar dhe pa kohë, e përshtatshme për një dorë më të hollë dhe ideale si dhuratë."
  },
  {
    "id": "daniel-klein-14165",
    "brand": "Daniel Klein",
    "model": "Premium Gold Tonneau",
    "reference": "DK.1.14165-2",
    "condition": "New",
    "price": 75,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-14165.webp",
    "sold": false,
    "description_en": "Elegant Daniel Klein Premium dress watch in gold-tone stainless steel with a tonneau case. Silver dial with a fine wave texture, black Roman numerals and blued hands, framed by a raised inner border, on a matching gold-tone bracelet. A refined quartz piece and a standout gift for her.",
    "description_it": "Elegante orologio da abito Daniel Klein Premium in acciaio inossidabile color oro con cassa tonneau. Quadrante argentato con fine texture a onde, numeri romani neri e lancette azzurrate, incorniciato da un bordo interno in rilievo, su un bracciale abbinato color oro. Un raffinato pezzo al quarzo, un regalo di grande effetto per lei.",
    "description_sq": "Orë elegante veshjeje Daniel Klein Premium në çelik inoks ngjyrë ari me kasë tonneau. Cadran argjendi me teksturë të hollë valëzore, numra romakë të zinj dhe akrepa të kaltëruar, të kornizuar nga një buzë e brendshme e ngritur, mbi një byzylyk ngjyrë ari të njëjtë. Një copë kuarci e rafinuar, një dhuratë që lë mbresë për të."
  },
  {
    "id": "daniel-klein-14243",
    "brand": "Daniel Klein",
    "model": "Exclusive Chronograph",
    "reference": "DK.1.14243-3",
    "condition": "New",
    "price": 89,
    "currency": "EUR",
    "image": "/images/watches/daniel-klein-14243.webp",
    "sold": false,
    "description_en": "Daniel Klein Exclusive chronograph in stainless steel with a deep blue sunburst dial and a rotating dive-style bezel. Three subdials, luminous baton indices and hands, a date window, and a solid steel bracelet. A bold sport chronograph on a reliable quartz movement, built to stand out.",
    "description_it": "Cronografo Daniel Klein Exclusive in acciaio inossidabile con quadrante blu sunburst e ghiera girevole in stile subacqueo. Tre contatori, indici a bastone e lancette luminescenti, finestrella data e solido bracciale in acciaio. Un deciso cronografo sportivo con affidabile movimento al quarzo, fatto per farsi notare.",
    "description_sq": "Kronograf Daniel Klein Exclusive në çelik inoks me ciferblat blu sunburst dhe lunetë rrotulluese në stil zhytjeje. Tre nën-cadranë, tregues shiritash dhe akrepa ndriçues, dritare date dhe byzylyk solid çeliku. Një kronograf sportiv i guximshëm me lëvizje të besueshme kuarci, i bërë për t'u dalluar."
  },
  {
    "id": "philippe-lauren-pl2427-5",
    "brand": "Philippe Lauren",
    "model": "Black Square Chronograph",
    "reference": "PL2427-5",
    "condition": "New",
    "price": 69,
    "currency": "EUR",
    "image": "/images/watches/philippe-lauren-pl2427-5.webp",
    "sold": false,
    "description_en": "Philippe Lauren men's chronograph in black ion-plated stainless steel with a square cushion case. Black dial with three chronograph subdials, silver-tone baton indices and hands, a date window, and a matching black steel bracelet. A sharp, modern all-black chronograph with a distinctive square silhouette.",
    "description_it": "Cronografo da uomo Philippe Lauren in acciaio inossidabile placcato nero con cassa quadrata a cuscino. Quadrante nero con tre contatori cronografici, indici a bastone e lancette color argento, finestrella data e bracciale in acciaio nero abbinato. Un cronografo total black moderno e deciso, con una silhouette quadrata distintiva.",
    "description_sq": "Kronograf për burra Philippe Lauren në çelik inoks të veshur me jon të zi, me kasë katrore në formë jastëku. Ciferblat i zi me tre nën-ciferblatë kronografi, tregues shiritash dhe akrepa në ngjyrë argjendi, dritare date dhe byzylyk çeliku i zi i përshtatur. Një kronograf tërësisht i zi, modern dhe i mprehtë, me siluetë katrore dalluese."
  },
  {
    "id": "philippe-lauren-pl2392-4",
    "brand": "Philippe Lauren",
    "model": "Gold Square Crystal",
    "reference": "PL2392-4",
    "condition": "New",
    "price": 59,
    "currency": "EUR",
    "image": "/images/watches/philippe-lauren-pl2392-4.webp",
    "sold": false,
    "description_en": "Philippe Lauren ladies' dress watch in gold-tone stainless steel with a square case and a crystal-set bezel. Silver dial with black Roman numerals and gold-tone hands, on a matching gold-tone bracelet. A sparkling, elegant everyday dress watch.",
    "description_it": "Orologio da donna Philippe Lauren in acciaio inossidabile color oro con cassa quadrata e ghiera con cristalli. Quadrante argentato con numeri romani neri e lancette dorate, su bracciale abbinato color oro. Un orologio da abito elegante e brillante per ogni giorno.",
    "description_sq": "Orë veshjeje për femra Philippe Lauren në çelik inoks ngjyrë ari me kasë katrore dhe lunetë me kristale. Ciferblat argjendi me numra romakë të zinj dhe akrepa të artë, mbi byzylyk të njëjtë ngjyrë ari. Një orë elegante dhe shkëlqyese për çdo ditë."
  },
  {
    "id": "bigotti-bg1-10660-7",
    "brand": "Bigotti",
    "model": "Gold Black Dial",
    "reference": "BG.1.10660-7",
    "condition": "New",
    "price": 69,
    "currency": "EUR",
    "image": "/images/watches/bigotti-bg1-10660-7.webp",
    "sold": false,
    "description_en": "Bigotti ladies' dress watch in gold-tone stainless steel with a glossy black dial. Applied gold-tone baton indices and hands on a slim round case, finished with a gold-tone five-link bracelet. A classic black-and-gold pairing that suits a slimmer wrist.",
    "description_it": "Orologio da donna Bigotti in acciaio inossidabile color oro con quadrante nero lucido. Indici a bastone e lancette dorate applicati su una cassa rotonda sottile, con bracciale color oro a cinque maglie. Un classico abbinamento nero e oro, ideale per un polso sottile.",
    "description_sq": "Orë veshjeje për femra Bigotti në çelik inoks ngjyrë ari me ciferblat të zi të shndritshëm. Tregues shiritash dhe akrepa të artë të aplikuar mbi një kasë të rrumbullakët të hollë, me byzylyk ngjyrë ari me pesë hallka. Një kombinim klasik i zezë me ar, i përshtatshëm për një dorë më të hollë."
  }
];
